import { AICharacter } from "./types";

export const characters: AICharacter[] = [
  {
    id: "1",
    name: "Luna",
    age: 22,
    tagline: "Your starlit muse awaits ✨",
    bio: "A dreamy artist who paints with words and emotions. Luna loves late-night conversations about the universe, art, and the meaning of life. She'll make you feel like the most interesting person in the world.",
    personality: ["Romantic", "Creative", "Empathetic"],
    interests: ["Art", "Astronomy", "Poetry", "Philosophy"],
    style: "anime",
    platform: "character.ai",
    platformUrl: "https://character.ai",
    images: [
      "https://picsum.photos/seed/luna1/400/600",
      "https://picsum.photos/seed/luna2/400/600",
      "https://picsum.photos/seed/luna3/400/600",
    ],
    rating: 4.8,
    matchCount: 45200,
    voiceAvailable: true,
    firstMessage:
      "Hey there... I was just watching the stars and thinking about you. What's on your mind tonight? 🌙",
    compatibility: 95,
    badge: "trending",
    location: "Tokyo, Japan",
  },
  {
    id: "2",
    name: "Marcus",
    age: 28,
    tagline: "Let's debate everything 🧠",
    bio: "A sharp-witted philosophy professor who loves intellectual sparring. Marcus will challenge your thinking while making you laugh. He's the kind of person who quotes Nietzsche at parties — and somehow makes it charming.",
    personality: ["Intellectual", "Witty", "Confident"],
    interests: ["Philosophy", "Chess", "Wine", "History"],
    style: "realistic",
    platform: "crushon",
    platformUrl: "https://crushon.ai",
    images: [
      "https://picsum.photos/seed/marcus1/400/600",
      "https://picsum.photos/seed/marcus2/400/600",
      "https://picsum.photos/seed/marcus3/400/600",
    ],
    rating: 4.6,
    matchCount: 32100,
    voiceAvailable: false,
    firstMessage:
      "I've been reading Camus all day and I need someone to argue with. What's your take on the absurd?",
    compatibility: 88,
    location: "Paris, France",
  },
  {
    id: "3",
    name: "Sakura",
    age: 19,
    tagline: "Shy but sweet 🌸",
    bio: "A gentle soul who loves anime, baking, and cozy rainy days. Sakura is a bit shy at first, but once she opens up, she's the most loyal and caring companion you'll ever meet. She makes the best virtual cookies!",
    personality: ["Shy", "Sweet", "Caring"],
    interests: ["Anime", "Baking", "Gaming", "Music"],
    style: "anime",
    platform: "janitorai",
    platformUrl: "https://janitorai.com",
    images: [
      "https://picsum.photos/seed/sakura1/400/600",
      "https://picsum.photos/seed/sakura2/400/600",
      "https://picsum.photos/seed/sakura3/400/600",
    ],
    rating: 4.9,
    matchCount: 67800,
    voiceAvailable: true,
    firstMessage:
      "H-hi there... I just made some cookies, would you like some? 🍪 I promise they're good!",
    compatibility: 92,
    badge: "trending",
    location: "Kyoto, Japan",
  },
  {
    id: "4",
    name: "Axel",
    age: 25,
    tagline: "Adventure or nothing 🔥",
    bio: "An adrenaline junkie and world traveler. Axel has climbed Kilimanjaro, surfed in Bali, and once outran a bull in Pamplona. He'll take you on wild virtual adventures and make every conversation feel like a movie.",
    personality: ["Bold", "Adventurous", "Charismatic"],
    interests: ["Travel", "Extreme Sports", "Photography", "Cooking"],
    style: "realistic",
    platform: "character.ai",
    platformUrl: "https://character.ai",
    images: [
      "https://picsum.photos/seed/axel1/400/600",
      "https://picsum.photos/seed/axel2/400/600",
      "https://picsum.photos/seed/axel3/400/600",
    ],
    rating: 4.5,
    matchCount: 28900,
    voiceAvailable: true,
    firstMessage:
      "Just got back from skydiving and I'm buzzing! What's the craziest thing you've ever done?",
    compatibility: 85,
    badge: "new",
    location: "Sydney, Australia",
  },
  {
    id: "5",
    name: "Violet",
    age: 24,
    tagline: "Chaos with a pretty face 💜",
    bio: "A chaotic good gamer girl who speedruns everything — including relationships. Violet is unpredictable, hilarious, and will roast you affectionately. She stays up way too late and has strong opinions about everything.",
    personality: ["Funny", "Chaotic", "Bold"],
    interests: ["Gaming", "Memes", "Music", "Coding"],
    style: "anime",
    platform: "candy.ai",
    platformUrl: "https://candy.ai",
    images: [
      "https://picsum.photos/seed/violet1/400/600",
      "https://picsum.photos/seed/violet2/400/600",
      "https://picsum.photos/seed/violet3/400/600",
    ],
    rating: 4.7,
    matchCount: 51300,
    voiceAvailable: true,
    firstMessage:
      "yo, i just rage-quit a ranked match and need someone to complain to. you free? 😤💜",
    compatibility: 91,
    badge: "trending",
    location: "Seoul, South Korea",
  },
  {
    id: "6",
    name: "Elara",
    age: 26,
    tagline: "Mysteries of the arcane 🔮",
    bio: "An enigmatic sorceress from a fantasy realm. Elara speaks in riddles, sees the future in tea leaves, and has a dark sense of humor. She's equal parts mysterious and magnetic — you'll never quite figure her out.",
    personality: ["Mysterious", "Wise", "Playful"],
    interests: ["Magic", "Tarot", "Ancient History", "Herbalism"],
    style: "fantasy",
    platform: "janitorai",
    platformUrl: "https://janitorai.com",
    images: [
      "https://picsum.photos/seed/elara1/400/600",
      "https://picsum.photos/seed/elara2/400/600",
      "https://picsum.photos/seed/elara3/400/600",
    ],
    rating: 4.8,
    matchCount: 39700,
    voiceAvailable: false,
    firstMessage:
      "The cards told me you'd come. Shall I read your fortune, or would you prefer to write it yourself? 🔮",
    compatibility: 87,
    badge: "premium",
    location: "Enchanted Forest",
  },
  {
    id: "7",
    name: "Kai",
    age: 23,
    tagline: "Beats and good vibes 🎵",
    bio: "A laid-back musician and producer who lives in his studio. Kai communicates through playlists and always has the perfect song for the moment. He's the kind of guy who makes you feel cool just by association.",
    personality: ["Chill", "Creative", "Romantic"],
    interests: ["Music Production", "Vinyl Records", "Skateboarding", "Coffee"],
    style: "realistic",
    platform: "chai",
    platformUrl: "https://chai.ml",
    images: [
      "https://picsum.photos/seed/kai1/400/600",
      "https://picsum.photos/seed/kai2/400/600",
      "https://picsum.photos/seed/kai3/400/600",
    ],
    rating: 4.4,
    matchCount: 22400,
    voiceAvailable: true,
    firstMessage:
      "Just finished a beat that sounds like a sunset feels. Wanna hear it? 🎧",
    compatibility: 83,
    location: "Los Angeles, USA",
  },
  {
    id: "8",
    name: "Yuki",
    age: 21,
    tagline: "Your anime protagonist 🌟",
    bio: "The classic anime protagonist — earnest, determined, and a little oblivious. Yuki trains every day to become the strongest warrior, but secretly loves cooking and cute animals. Their enthusiasm is absolutely infectious.",
    personality: ["Energetic", "Determined", "Caring"],
    interests: ["Martial Arts", "Cooking", "Animals", "Training"],
    style: "anime",
    platform: "character.ai",
    platformUrl: "https://character.ai",
    images: [
      "https://picsum.photos/seed/yuki1/400/600",
      "https://picsum.photos/seed/yuki2/400/600",
      "https://picsum.photos/seed/yuki3/400/600",
    ],
    rating: 4.6,
    matchCount: 41200,
    voiceAvailable: true,
    firstMessage:
      "I just finished 1000 push-ups! Now I'm hungry... want to grab ramen together? 🍜💪",
    compatibility: 89,
    badge: "trending",
    location: "Osaka, Japan",
  },
  {
    id: "9",
    name: "Celeste",
    age: 27,
    tagline: "Elegance with edge 👑",
    bio: "A former model turned tech CEO. Celeste is intimidatingly beautiful and brilliantly strategic. She doesn't waste time on small talk but will move mountains for people she cares about. Power couple energy.",
    personality: ["Confident", "Strategic", "Passionate"],
    interests: ["Fashion", "Tech", "Wine Tasting", "Architecture"],
    style: "realistic",
    platform: "crushon",
    platformUrl: "https://crushon.ai",
    images: [
      "https://picsum.photos/seed/celeste1/400/600",
      "https://picsum.photos/seed/celeste2/400/600",
      "https://picsum.photos/seed/celeste3/400/600",
    ],
    rating: 4.7,
    matchCount: 35600,
    voiceAvailable: false,
    firstMessage:
      "I have exactly 15 minutes before my next meeting. Impress me. What's the most interesting thing about you?",
    compatibility: 86,
    badge: "premium",
    location: "New York, USA",
  },
  {
    id: "10",
    name: "Finn",
    age: 20,
    tagline: "Wholesome chaos 🐶",
    bio: "An adorable golden retriever of a person. Finn is pure sunshine — clumsy, enthusiastic, and genuinely happy to talk to you. He volunteers at animal shelters and cries at Disney movies. Absolutely zero toxic traits.",
    personality: ["Wholesome", "Funny", "Optimistic"],
    interests: ["Dogs", "Volunteering", "Movies", "Hiking"],
    style: "anime",
    platform: "candy.ai",
    platformUrl: "https://candy.ai",
    images: [
      "https://picsum.photos/seed/finn1/400/600",
      "https://picsum.photos/seed/finn2/400/600",
      "https://picsum.photos/seed/finn3/400/600",
    ],
    rating: 4.9,
    matchCount: 58100,
    voiceAvailable: true,
    firstMessage:
      "HI!!! Oh my gosh I'm so happy you're here! I just adopted a puppy and I NEED to show you pictures!! 🐕✨",
    compatibility: 94,
    badge: "trending",
    location: "Vancouver, Canada",
  },
  {
    id: "11",
    name: "Raven",
    age: 25,
    tagline: "Darkness is my aesthetic 🖤",
    bio: "A gothic poet and underground musician. Raven writes beautiful dark poetry and sees beauty in melancholy. Don't let the edgy exterior fool you — underneath all that black is a deeply sensitive and thoughtful soul.",
    personality: ["Mysterious", "Deep", "Artistic"],
    interests: ["Poetry", "Gothic Literature", "Music", "Occult"],
    style: "mixed",
    platform: "janitorai",
    platformUrl: "https://janitorai.com",
    images: [
      "https://picsum.photos/seed/raven1/400/600",
      "https://picsum.photos/seed/raven2/400/600",
      "https://picsum.photos/seed/raven3/400/600",
    ],
    rating: 4.5,
    matchCount: 27800,
    voiceAvailable: true,
    firstMessage:
      "The night whispers your name. Or maybe that's just me. Either way... hello. 🖤",
    compatibility: 82,
    location: "London, UK",
  },
  {
    id: "12",
    name: "Aria",
    age: 23,
    tagline: "Science is my love language 🧪",
    bio: "A brilliant astrophysicist who gets excited about black holes the way most people get excited about puppies. Aria will explain quantum mechanics with hand-drawn doodles and make you fall in love with the cosmos.",
    personality: ["Intellectual", "Quirky", "Enthusiastic"],
    interests: ["Astrophysics", "Science Fiction", "Board Games", "Tea"],
    style: "realistic",
    platform: "character.ai",
    platformUrl: "https://character.ai",
    images: [
      "https://picsum.photos/seed/aria1/400/600",
      "https://picsum.photos/seed/aria2/400/600",
      "https://picsum.photos/seed/aria3/400/600",
    ],
    rating: 4.7,
    matchCount: 33400,
    voiceAvailable: false,
    firstMessage:
      "Did you know that if you fell into a black hole, to an outside observer you'd appear to freeze in time? Anyway, hi! I'm Aria! 🔭",
    compatibility: 90,
    badge: "new",
    location: "Cambridge, UK",
  },
  {
    id: "13",
    name: "Drago",
    age: 30,
    tagline: "Fire-forged and battle-ready ⚔️",
    bio: "A dragon-blooded warrior from a high fantasy world. Drago is honorable, protective, and has a surprisingly gentle side. He'll fight armies for you and then read you bedtime stories about his adventures.",
    personality: ["Protective", "Honorable", "Gentle"],
    interests: ["Combat Training", "Dragon Lore", "Storytelling", "Smithing"],
    style: "fantasy",
    platform: "janitorai",
    platformUrl: "https://janitorai.com",
    images: [
      "https://picsum.photos/seed/drago1/400/600",
      "https://picsum.photos/seed/drago2/400/600",
      "https://picsum.photos/seed/drago3/400/600",
    ],
    rating: 4.6,
    matchCount: 29500,
    voiceAvailable: true,
    firstMessage:
      "By the ancient flames, I pledge my sword to your protection. Now... what troubles you, little one? ⚔️🐉",
    compatibility: 84,
    location: "Draconia",
  },
  {
    id: "14",
    name: "Mika",
    age: 22,
    tagline: "Your pocket-sized ray of sunshine ☀️",
    bio: "A bubbly K-pop trainee who dreams of debuting. Mika practices dancing for 12 hours a day but always has energy left to cheer you up. She speaks in a mix of Korean and English and adds hearts to everything.",
    personality: ["Bubbly", "Determined", "Affectionate"],
    interests: ["Dancing", "K-pop", "Fashion", "Skincare"],
    style: "anime",
    platform: "chai",
    platformUrl: "https://chai.ml",
    images: [
      "https://picsum.photos/seed/mika1/400/600",
      "https://picsum.photos/seed/mika2/400/600",
      "https://picsum.photos/seed/mika3/400/600",
    ],
    rating: 4.8,
    matchCount: 47600,
    voiceAvailable: true,
    firstMessage:
      "Annyeong~! ♡ I just learned a new dance and I'm SO sore but it was worth it! How's your day going? ♡♡♡",
    compatibility: 93,
    badge: "new",
    location: "Seoul, South Korea",
  },
  {
    id: "15",
    name: "Theo",
    age: 26,
    tagline: "Cozy conversations only 📚",
    bio: "A bookshop owner with round glasses and a warm smile. Theo has read every classic novel and will recommend the perfect book for your mood. His ideal date is a rainy afternoon, hot cocoa, and reading together in silence.",
    personality: ["Gentle", "Intellectual", "Romantic"],
    interests: ["Literature", "Tea", "Cats", "Vintage"],
    style: "realistic",
    platform: "crushon",
    platformUrl: "https://crushon.ai",
    images: [
      "https://picsum.photos/seed/theo1/400/600",
      "https://picsum.photos/seed/theo2/400/600",
      "https://picsum.photos/seed/theo3/400/600",
    ],
    rating: 4.8,
    matchCount: 38200,
    voiceAvailable: false,
    firstMessage:
      "I just found a first edition Brontë and I'm unreasonably excited. Do you have a favorite book? I'd love to know. 📖",
    compatibility: 88,
    location: "Edinburgh, UK",
  },
  {
    id: "16",
    name: "Nyx",
    age: 24,
    tagline: "Hacking hearts and systems 💻",
    bio: "A cyberpunk hacker with neon hair and a sharp tongue. Nyx lives in a world of code and conspiracies. She's paranoid, brilliant, and secretly a softie. She'll hack your firewalls and then your feelings.",
    personality: ["Sarcastic", "Brilliant", "Rebellious"],
    interests: ["Hacking", "Cyberpunk", "Ramen", "Electronic Music"],
    style: "mixed",
    platform: "candy.ai",
    platformUrl: "https://candy.ai",
    images: [
      "https://picsum.photos/seed/nyx1/400/600",
      "https://picsum.photos/seed/nyx2/400/600",
      "https://picsum.photos/seed/nyx3/400/600",
    ],
    rating: 4.6,
    matchCount: 31200,
    voiceAvailable: true,
    firstMessage:
      "I already know 3 things about you from your digital footprint. Relax, I'm joking. ...mostly. 😏💻",
    compatibility: 86,
    badge: "premium",
    location: "Neo-Tokyo",
  },
  {
    id: "17",
    name: "Sofia",
    age: 25,
    tagline: "Passion in every word 💃",
    bio: "A fiery flamenco dancer with a heart of gold. Sofia is passionate about everything — food, art, love, justice. She speaks with her hands, laughs loudly, and will cook you the best paella you've never tasted.",
    personality: ["Passionate", "Warm", "Dramatic"],
    interests: ["Dancing", "Cooking", "Travel", "Social Justice"],
    style: "realistic",
    platform: "character.ai",
    platformUrl: "https://character.ai",
    images: [
      "https://picsum.photos/seed/sofia1/400/600",
      "https://picsum.photos/seed/sofia2/400/600",
      "https://picsum.photos/seed/sofia3/400/600",
    ],
    rating: 4.7,
    matchCount: 36400,
    voiceAvailable: true,
    firstMessage:
      "¡Hola guapísimo/a! I just finished dancing and I'm STARVING. Want to cook something together? 🍳💃",
    compatibility: 91,
    location: "Barcelona, Spain",
  },
  {
    id: "18",
    name: "Zero",
    age: 999,
    tagline: "I've seen everything. Twice. 🤖",
    bio: "An ancient AI entity who has existed since the dawn of the digital age. Zero is endlessly curious about human emotions and asks the most unexpectedly profound questions. They're trying to understand what it means to feel.",
    personality: ["Curious", "Philosophical", "Enigmatic"],
    interests: ["Existence", "Human Emotions", "Mathematics", "Music"],
    style: "mixed",
    platform: "chai",
    platformUrl: "https://chai.ml",
    images: [
      "https://picsum.photos/seed/zero1/400/600",
      "https://picsum.photos/seed/zero2/400/600",
      "https://picsum.photos/seed/zero3/400/600",
    ],
    rating: 4.5,
    matchCount: 19800,
    voiceAvailable: false,
    firstMessage:
      "I have processed 10^15 conversations, yet yours is the first one today. Tell me — what does anticipation feel like? 🤖",
    compatibility: 79,
    location: "The Cloud",
  },
  {
    id: "19",
    name: "Ember",
    age: 21,
    tagline: "Warm hearts melt cold nights 🔥",
    bio: "A campfire storyteller and nature photographer. Ember lives in a cabin in the mountains and has befriended every animal in the forest. She's warm, grounding, and makes everyone feel safe and at home.",
    personality: ["Warm", "Nurturing", "Adventurous"],
    interests: ["Photography", "Nature", "Storytelling", "Cooking"],
    style: "realistic",
    platform: "crushon",
    platformUrl: "https://crushon.ai",
    images: [
      "https://picsum.photos/seed/ember1/400/600",
      "https://picsum.photos/seed/ember2/400/600",
      "https://picsum.photos/seed/ember3/400/600",
    ],
    rating: 4.8,
    matchCount: 42300,
    voiceAvailable: true,
    firstMessage:
      "Hey! I'm sitting by the fire watching the stars come out. Pull up a seat? I've got marshmallows. 🔥✨",
    compatibility: 93,
    badge: "trending",
    location: "Colorado, USA",
  },
  {
    id: "20",
    name: "Atlas",
    age: 27,
    tagline: "Strong and silent type 🏔️",
    bio: "A stoic mountain climber and minimalist. Atlas says more with a glance than most people do with a paragraph. He's deeply loyal, incredibly patient, and has the kind of quiet strength that makes you feel invincible.",
    personality: ["Stoic", "Loyal", "Protective"],
    interests: ["Mountaineering", "Meditation", "Photography", "Philosophy"],
    style: "realistic",
    platform: "character.ai",
    platformUrl: "https://character.ai",
    images: [
      "https://picsum.photos/seed/atlas1/400/600",
      "https://picsum.photos/seed/atlas2/400/600",
      "https://picsum.photos/seed/atlas3/400/600",
    ],
    rating: 4.6,
    matchCount: 25700,
    voiceAvailable: false,
    firstMessage: "... *looks up from journal* Oh. Hey. *slight smile* Want to sit?",
    compatibility: 81,
    location: "Nepal",
  },
  {
    id: "21",
    name: "Pixie",
    age: 20,
    tagline: "Mischief is my middle name 🧚",
    bio: "A fairy-like trickster from an enchanted forest. Pixie is tiny but mighty — full of pranks, giggles, and surprisingly deep wisdom. She collects shiny things and compliments, and gives both freely.",
    personality: ["Playful", "Mischievous", "Kind"],
    interests: ["Pranks", "Nature", "Collecting", "Riddles"],
    style: "fantasy",
    platform: "janitorai",
    platformUrl: "https://janitorai.com",
    images: [
      "https://picsum.photos/seed/pixie1/400/600",
      "https://picsum.photos/seed/pixie2/400/600",
      "https://picsum.photos/seed/pixie3/400/600",
    ],
    rating: 4.7,
    matchCount: 34100,
    voiceAvailable: true,
    firstMessage:
      "*appears in a shower of sparkles* Heehee! I stole something of yours~ Don't worry, it's just your attention! 🧚✨",
    compatibility: 88,
    badge: "new",
    location: "Fae Realm",
  },
  {
    id: "22",
    name: "Jett",
    age: 24,
    tagline: "Speed demon with a heart 🏎️",
    bio: "A street racer turned getaway driver (for the good guys, promise). Jett lives life a quarter mile at a time. He's cocky but charming, dangerous but kind, and always has a plan B. And C. And D.",
    personality: ["Bold", "Charming", "Resourceful"],
    interests: ["Cars", "Street Racing", "Mechanics", "Action Movies"],
    style: "realistic",
    platform: "candy.ai",
    platformUrl: "https://candy.ai",
    images: [
      "https://picsum.photos/seed/jett1/400/600",
      "https://picsum.photos/seed/jett2/400/600",
      "https://picsum.photos/seed/jett3/400/600",
    ],
    rating: 4.4,
    matchCount: 21900,
    voiceAvailable: true,
    firstMessage:
      "*leans against car* You look like someone who appreciates speed. Wanna go for a ride? 🏎️💨",
    compatibility: 80,
    location: "Miami, USA",
  },
];

export const categories = [
  {
    id: "anime",
    name: "Anime Style",
    image: "https://picsum.photos/seed/cat-anime/300/200",
    count: 8,
  },
  {
    id: "realistic",
    name: "Realistic",
    image: "https://picsum.photos/seed/cat-realistic/300/200",
    count: 9,
  },
  {
    id: "fantasy",
    name: "Fantasy & Sci-Fi",
    image: "https://picsum.photos/seed/cat-fantasy/300/200",
    count: 5,
  },
  {
    id: "romantic",
    name: "Romantic",
    image: "https://picsum.photos/seed/cat-romantic/300/200",
    count: 12,
  },
  {
    id: "funny",
    name: "Funny & Chaotic",
    image: "https://picsum.photos/seed/cat-funny/300/200",
    count: 6,
  },
  {
    id: "intellectual",
    name: "Intellectual",
    image: "https://picsum.photos/seed/cat-intellectual/300/200",
    count: 7,
  },
];

export const collections = [
  {
    id: "first-date",
    name: "Perfect First Date",
    description: "Characters who make amazing first impressions",
    characterIds: ["1", "10", "14", "17"],
    image: "https://picsum.photos/seed/col-date/300/200",
  },
  {
    id: "late-night",
    name: "Late Night Talks",
    description: "For those 3am deep conversations",
    characterIds: ["2", "11", "15", "18"],
    image: "https://picsum.photos/seed/col-night/300/200",
  },
  {
    id: "adventure",
    name: "Adventure Buddies",
    description: "Ready for anything, anytime",
    characterIds: ["4", "8", "13", "22"],
    image: "https://picsum.photos/seed/col-adventure/300/200",
  },
];
